# For NeoForge 20.5+

modLoader="lowcodefml"
loaderVersion="[1,)"
license="MIT license"
issueTrackerURL="https://github.com/Iunius118/ToLaserBlade-ExtraModels/issues"

[[mods]]
modId="tlbexmodels"
version="${file.jarVersion}"
displayName="ToLaserBlade-ExtraModels"
displayURL="https://github.com/Iunius118/ToLaserBlade-ExtraModels"
logoFile="tlbexmodels_logo.png"
credits="Created by Iunius118."
authors="Iunius118"
description="A ToLaserBlade add-on to add more laser blade shapes."

[[dependencies.tlbexmodels]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tlbexmodels]]
    modId="tolaserblade"
    type="required"
    versionRange="[1.21.3,)"
    ordering="AFTER"
    side="BOTH"
